import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ title }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by Nirmalya" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <nav>
          <img />
          <a href="/">Home</a>
          <a href="/events">Events</a>
          <a href="/about-us">About Us</a>
        </nav>
      </header>

      <main className={styles.main}>
        <a href="">
          <img />
          <h2>{title}</h2>
          <p>
            A tiny VS Code extension made up of a few commands that generate and
            insert lorem ipsum text into a text file. To use the extension, open
            the command palette (F1 or cmd/ctrl+shift+p, type "lorem ipsum" and
            select to insert either a line or paragraph.
          </p>
        </a>
        <a href="">
          <img />
          <h2>Events in Kendrapara</h2>
          <p>
            A tiny VS Code extension made up of a few commands that generate and
            insert lorem ipsum text into a text file. To use the extension, open
            the command palette (F1 or cmd/ctrl+shift+p, type "lorem ipsum" and
            select to insert either a line or paragraph.
          </p>
        </a>
        <a href="">
          <img />
          <h2>Events in Odisha</h2>
          <p>
            A tiny VS Code extension made up of a few commands that generate and
            insert lorem ipsum text into a text file. To use the extension, open
            the command palette (F1 or cmd/ctrl+shift+p, type "lorem ipsum" and
            select to insert either a line or paragraph.
          </p>
        </a>
      </main>

      <footer className={styles.footer}>
        <p> © 2023 Nirmalya - A Project Built with Next.js </p>
      </footer>
    </>
  )
}

export function getServerSideProps() {
  return {
    props: {
      title: 'Test!',
    },
  }
}
