import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { HomePage } from '../src/components/home/home-page'

const inter = Inter({ subsets: ['latin'] })

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Events App</title>
        <meta name="description" content="Generated by Nirmalya" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <nav>
          <img />
          <Link href="/">Home</Link>
          <Link href="/events">Events</Link>
          <Link href="/about-us">About Us</Link>
        </nav>
      </header>

      <HomePage data={data} />

      <footer className={styles.footer}>
        <p> © 2023 Nirmalya - A Project Built with Next.js </p>
      </footer>
    </>
  )
}

export async function getServerSideProps() {
  const { events_categories } = await import('../data/data.json')
  // console.log(events_categories)

  return {
    props: {
      data: events_categories,
    },
  }
}
